name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Build Debug APK
      run: ./gradlew assembleDebug
